# user  nginx; # macOS에서는 실행 계정 권한을 따르거나 nobody 사용
worker_processes  auto;

error_log  /Users/deepblue/services/nginx/logs/error.log notice;
pid        /Users/deepblue/services/nginx/temp/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /opt/homebrew/etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    # 파일 업로드 크기 제한
    client_max_body_size 50m;

    geo $remote_addr $is_internal {
        default        0;
        127.0.0.1      1;
        192.168.0.0/16 1;
        100.64.0.0/10  1;
        172.16.0.0/12  1;
    }

    include /Users/deepblue/services/nginx/servers/*.conf;
}
